version: "3"
services:
  besu:
    image: hyperledger/besu:1.4.3
    container_name: besu
    environment:
      - BESU_P2P_HOST=${BESU_P2P_HOST}
    depends_on:
      - orion
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545
    volumes:
      - ./config/besu:/config/besu/
      - ./keys/besu/key:/opt/besu/data/key
      - besu-database:/opt/besu/data/database
    command: ["--config-file=/config/besu/config.toml"]

  prometheus:
    image: prom/prometheus:v2.15.2
    container_name: prometheus
    depends_on:
      - besu
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus

volumes:
  besu-database:
